import {assets,events,properties,challenges,placements,pricesAt,assetHistory,scenarioNames} from './data.mjs';
import {portfolioValue,challengeProgress} from './engine.mjs';
import {icon} from './icons.mjs';
export const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const number=(n,d=0)=>Number(n).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d});
export const money=(n,d=0)=>number(n,d)+' <span class="unit">VC</span>';
export const marketLabel=a=>a.handle||'$'+a.id;
export const avatar=(a,size='')=>a.id==='AURA'?'<img class="avatar auris-portrait '+size+'" src="./assets/auris.jpg" alt="" width="65" height="65">':'<span class="avatar '+size+'" style="--avatar-x:'+((a.avatar%3)*50)+'%;--avatar-y:'+(Math.floor(a.avatar/3)*100)+'%" aria-hidden="true"></span>';
export const propertyImage=p=>'<img class="property-image" src="./assets/lots/'+esc(p.id)+'.png" alt="'+esc(p.name+' — '+p.kind)+'" loading="lazy" decoding="async">';
export function chart(values,color='violet',large=false){
  const width=large?440:160,height=large?155:42,min=Math.min(...values),max=Math.max(...values),range=Math.max(max-min,max*.012);
  const points=values.map((v,i)=>[8+i*(width-16)/(values.length-1||1),height-8-(v-min+(range-(max-min))/2)*(height-16)/range]);
  const path=points.map((p,i)=>(i?'L':'M')+p.map(n=>n.toFixed(2)).join(' ')).join(' ');
  return '<svg class="chart '+(large?'large':'')+' '+color+'" viewBox="0 0 '+width+' '+height+'" role="img" aria-label="'+(large?'Demo value history':'Demo price trend')+'">'+
  (large?'<path class="chart-fill" d="'+path+' L'+(width-8)+' '+height+' L8 '+height+'Z"/>':'')+
  '<path class="chart-line" d="'+path+'"/>'+(large?'<circle cx="'+points.at(-1)[0]+'" cy="'+points.at(-1)[1]+'" r="4" fill="currentColor"/>':'')+'</svg>';
}
export const navItems=[['discover','Discover'],['markets','Markets'],['events','Events & Bets'],['challenges','Challenges'],['city','Virtu City'],['portfolio','Portfolio']];
export function exchangeTape(){
  const signals=assets.filter(a=>a.category==='Influencers'||a.category==='Trends');
  const quotes=signals.map(a=>'<span class="culture-quote"><strong>'+marketLabel(a)+'</strong><span>'+a.audience+' audience</span><b class="'+(a.change>=0?'positive':'negative')+'">'+(a.change>0?'+':'')+number(a.change,2)+'%</b><span>ATTN '+a.attention+'</span></span>').join('');
  return '<section class="exchange-board" aria-label="Real-world public markets and simulated SMSX influence signals"><div class="tape-row public-tape"><span class="tape-label"><strong>BRAND MARKETS</strong><small>LIVE / DELAYED</small></span><div class="tradingview-shell"><div class="market-fallback" aria-hidden="true">META · GOOGL · SNAP · PINS · AMZN · AAPL · NFLX · DIS · NKE · NVDA <span>CONNECTING TO MARKET FEED</span></div></div></div><div class="tape-row culture-tape"><span class="tape-label"><strong>CREATOR SIGNAL</strong><small>SIMULATED</small></span><div class="culture-window"><div class="culture-track">'+quotes+'<span class="culture-repeat" aria-hidden="true">'+quotes+'</span></div></div></div></section>';
}
export function shell(s,ui){
  return '<aside class="sidebar"><a href="#discover" class="brand" aria-label="SMSX Discover">SMS<span class="brand-x">X</span><small>SOCIAL MEDIA<br>STOCK XCHANGE</small></a><nav aria-label="Main">'+
  navItems.map(([id,label])=>'<button class="nav-item '+(ui.view===id?'active':'')+'" data-view="'+id+'"'+(ui.view===id?' aria-current="page"':'')+'>'+icon(id)+'<span>'+label+'</span></button>').join('')+
  '</nav><div class="sidebar-foot">A FAME FARM EXPERIENCE</div></aside><div class="workspace"><header class="topbar"><form class="search" role="search">'+icon('search')+
  '<input id="market-search" aria-label="Search markets, people, trends" placeholder="Search markets, people, trends" value="'+esc(ui.search)+'" autocomplete="off"><button class="search-clear" type="button" data-clear-search aria-label="Clear search" '+(!ui.search?'hidden':'')+'>'+icon('close')+'</button></form><button class="balance" data-view="portfolio" aria-label="Portfolio value '+number(portfolioValue(s))+' VirtuCoin"><span class="coin">V</span>'+money(portfolioValue(s))+'</button><button class="demo-pill" data-demo>DEMO</button>'+avatar({avatar:5},'account')+'</header>'+exchangeTape()+'<main id="main-content" tabindex="-1">'+content(s,ui)+'</main><footer class="app-footer"><span>SMSX × FAME FARM</span><span>Interactive demo · Simulated data · VirtuCoin has no cash value</span><button data-demo>How this demo works '+icon('arrow')+'</button></footer></div>';
}
function heading(title,sub,action=''){return '<div class="page-heading"><div><h1>'+title+'</h1><p>'+sub+'</p></div>'+action+'</div>';}
function campaign(s){
  const booking=s.campaigns.find(c=>c.placement==='discover'&&c.ends>s.day);
  return '<section class="campaign"><div class="campaign-art art shoes" role="img" aria-label="Iridescent chrome sneakers on lavender steps"></div><div class="campaign-copy"><span class="sponsor-label">'+(booking?'Your demo placement':'Sponsored')+'</span><h1>'+esc(booking?booking.name:'CHROME CARPET')+'</h1><p>'+(booking?'Your brand. Front and center.':'The next drop is yours.')+'</p><button class="button purple" '+(booking?'data-ad="discover"':'data-asset="CHRM"')+'>'+(booking?'View booking':'Explore drop')+' '+icon('arrow')+'</button></div></section>';
}
function stats(){return '<div class="market-stats panel"><div><span class="stat-icon purple">'+icon('markets')+'</span><span><small>Culture index</small><strong>128.42 <em class="positive">+4.8%</em></strong></span></div><div><span class="stat-icon blue">'+icon('volume')+'</span><span><small>Volume</small><strong>2.4M VC</strong></span></div><button data-asset="CLIME"><span class="stat-icon lime">'+icon('markets')+'</span><span><small>Trending</small><strong>#ClimeCore</strong></span></button></div>';}
export function marketRows(s,list){
  const prices=pricesAt(s.day);
  return list.length?list.map(a=>'<div class="market-row"><button class="asset-name" data-asset="'+a.id+'">'+avatar(a)+'<span><strong>'+a.name+'</strong><small>'+marketLabel(a)+'</small></span></button><button class="market-price" data-asset="'+a.id+'" aria-label="Trade '+a.name+'">'+money(prices[a.id],2)+'</button><span class="change '+(a.change>=0?'positive':'negative')+'">'+(a.change>0?'+':'')+number(a.change,2)+'%</span><button class="spark-button" data-asset="'+a.id+'" aria-label="View '+a.name+' chart">'+chart(assetHistory(a,s.day),a.change>0?'green':'coral')+'</button><button class="watch '+(s.watch.includes(a.id)?'watched':'')+'" data-watch="'+a.id+'" aria-label="'+(s.watch.includes(a.id)?'Remove ':'Watch ')+a.name+'" aria-pressed="'+s.watch.includes(a.id)+'">'+icon('star')+'</button></div>').join(''):'<div class="empty">No markets match that search. Try a name, ticker, or category.</div>';
}
function filterChips(ui,full=false){return '<div class="filters" role="group" aria-label="Market categories">'+(full?['All','Influencers','Fashion','Trends','Brands','Events','Music','Watchlist']:['All','Influencers','Fashion','Trends','Brands']).map(f=>'<button data-filter="'+f+'" class="chip '+(ui.filter===f?'selected':'')+'" aria-pressed="'+(ui.filter===f)+'">'+f+'</button>').join('')+'</div>';}
function filtered(s,ui){return assets.filter(a=>(ui.filter==='All'||a.category===ui.filter||(ui.filter==='Watchlist'&&s.watch.includes(a.id)))&&(!ui.search||(a.name+' '+marketLabel(a)+' '+a.id+' '+a.category+' '+a.world).toLowerCase().includes(ui.search.toLowerCase())));}
function portfolioCard(s){
  const val=portfolioValue(s),performance=(val-25000)/25000*100;
  return '<section class="panel portfolio-card"><h2>Your portfolio</h2><strong class="portfolio-amount">'+money(val)+'</strong><span class="portfolio-change '+(performance>=0?'positive':'negative')+'">'+(performance>0?'+':'')+number(performance,2)+'% this demo</span><div class="portfolio-chart">'+chart(s.history.length>1?s.history:[25000,25000,25000,25000],'violet',true)+'</div><div class="chart-axis"><span>Opening balance</span><span>Now</span></div><button class="button outline full" data-view="portfolio">View portfolio</button></section>';
}
function prediction(s,e,compact=false){
  const closed=s.day>=e.closes;
  return '<article class="prediction-card '+(compact?'compact':'')+'"><div class="prediction-top"><span class="prediction-icon">'+icon('volume')+'</span><div><small class="coral-text">'+(closed?'SETTLED':'PREDICTION')+'</small><h3>'+e.title+'</h3><p>'+(closed?'Resolved '+(e.outcome?'Yes':'No')+' · Demo day '+e.closes:'Closes in '+(e.closes-s.day)+' demo day'+(e.closes-s.day===1?'':'s'))+'</p></div><strong class="probability">'+(closed?(e.outcome?'Yes':'No'):e.yes+'%')+'</strong></div><div class="probability-bar"><span style="width:'+e.yes+'%">'+e.yes+'%</span><span style="width:'+(100-e.yes)+'%">'+(100-e.yes)+'%</span></div><div class="bet-actions"><button class="button lime" data-bet="'+e.id+'" data-side="yes" '+(closed?'disabled':'')+'>Yes <span>'+e.yes+'%</span></button><button class="button coral" data-bet="'+e.id+'" data-side="no" '+(closed?'disabled':'')+'>No <span>'+(100-e.yes)+'%</span></button></div></article>';
}
function features(){return '<div class="features"><article class="feature city-feature"><div class="art city-art" role="img" aria-label="White futuristic towers and a bright plaza in Prime Square"></div><div class="feature-copy"><h2>Prime Square</h2><p>Own your place in Virtu City.</p><button class="button lime" data-view="city">Claim your address '+icon('arrow')+'</button></div></article><article class="feature gala-feature"><div class="art gala-art" role="img" aria-label="Silver and lavender couture on a futuristic runway"></div><div class="feature-copy"><h2>Meta Gala</h2><p>Where culture<br>becomes legend.</p><button class="button lavender" data-bet="gala" data-side="yes">Explore event '+icon('arrow')+'</button></div></article></div>';}
function discover(s,ui){
  return campaign(s)+'<div class="discover-grid"><div class="rise-column">'+stats()+'<section class="panel rise-panel"><div class="panel-heading"><h2>On the rise</h2>'+filterChips(ui)+'</div><div id="market-results">'+marketRows(s,filtered(s,ui).slice(0,5))+'</div></section></div><aside class="right-column">'+portfolioCard(s)+prediction(s,events[0],true)+'</aside></div>'+features();
}
function markets(s,ui){
  return heading('Markets','Spot the next wave. Make your move.','<span class="small-tag">Demo day '+s.day+'</span>')+'<div class="market-page-grid"><section class="panel market-page"><div class="panel-heading">'+filterChips(ui,true)+'</div><div class="table-caption"><span>Market</span><span>Price</span><span>Change</span><span>Trend</span><span></span></div><div id="market-results">'+marketRows(s,filtered(s,ui))+'</div></section><aside class="right-column">'+portfolioCard(s)+'<section class="panel mirror-note"><span class="small-tag">Reality mirror</span><h3>The world, reflected.</h3><p>Culture-inspired indices sit alongside Fame Farm’s own markets. Every price and statistic here is simulated.</p><button class="text-button" data-asset="STRT">Explore Streetwear Index '+icon('arrow')+'</button></section></aside></div>';
}
function eventPage(s){
  const activeCampaign=s.campaigns.find(c=>c.placement==='event'&&c.ends>s.day);
  return heading('Events & Bets','Back your read on what happens next.','<button class="button outline" data-advance '+(s.day>=6?'disabled':'')+'>Advance demo day '+icon('arrow')+'</button>')+
  '<div class="day-strip"><span class="live-dot"></span><strong>Demo day '+s.day+' / 6</strong><span>'+scenarioNames[Math.min(s.day,5)]+'</span><button class="text-button" data-demo>How outcomes work</button></div>'+
  (activeCampaign?'<div class="sponsored-strip"><span>Sponsored · Demo</span><strong>'+esc(activeCampaign.name)+'</strong></div>':'')+
  '<div class="event-grid">'+events.map(e=>'<div class="event-item"><div class="event-image '+e.image+'">'+(e.asset==='AURA'?'<img class="event-portrait" src="./assets/auris.jpg" alt="Auris" width="1178" height="1184" loading="lazy">':(e.image==='gala'||e.image==='shoes')?'<div class="art '+(e.image==='gala'?'gala-art':'shoes')+'"></div>':'<span class="event-symbol">'+(e.asset==='CLIME'?'#':e.asset==='NANOQ'?'NQ':'FM')+'</span>')+'<span class="event-category">'+e.category+'</span></div>'+prediction(s,e)+'</div>').join('')+'</div><div class="ad-invitation"><div><strong>Put your brand in the moment.</strong><p>Book a sponsored event placement with demo VirtuCoin.</p></div><button class="button purple" data-ad="event">Explore ad space '+icon('arrow')+'</button></div>';
}
function challengePage(s){
  return heading('Challenges','Good instincts deserve a little extra.')+'<div class="challenge-intro"><span class="stat-icon lime">'+icon('challenges')+'</span><div><h2>Build a portfolio. Collect the wins.</h2><p>Join for free, complete the goal, and claim your demo VirtuCoin.</p></div><strong>'+s.claimed.length+' / 3<span>completed</span></strong></div><div class="challenge-grid">'+challenges.map(c=>{
    const joined=s.joined.includes(c.id),claimed=s.claimed.includes(c.id),progress=challengeProgress(s,c),done=progress>=c.target;
    return '<article class="panel challenge-card '+c.color+'"><div class="challenge-card-top"><span class="stat-icon '+c.color+'">'+icon(c.kind==='property'?'city':c.kind==='fashion'?'star':'markets')+'</span><span class="small-tag">'+c.tag+'</span></div><h2>'+c.title+'</h2><p>'+c.description+'</p><strong class="reward">+'+c.reward+' <span>VC reward</span></strong><div class="progress-track"><span style="width:'+(progress/c.target*100)+'%"></span></div><div class="progress-label"><span>'+progress+' / '+c.target+' complete</span><span>'+(claimed?'Claimed':joined?'Joined':'Free to join')+'</span></div><button class="button '+(claimed?'outline':joined&&done?'lime':'purple')+' full" '+(claimed?'disabled':!joined?'data-join="'+c.id+'"':done?'data-claim="'+c.id+'"':'data-view="'+(c.kind==='property'?'city':'markets')+'"')+'>'+(claimed?'Reward claimed':!joined?'Join challenge':done?'Claim '+c.reward+' VC':'Continue challenge')+(claimed?' '+icon('check'):' '+icon('arrow'))+'</button></article>';
  }).join('')+'</div><section class="challenge-event"><div><span class="small-tag">Trending challenge</span><h2>#ClimeCore</h2><p>One challenge. A whole city watching.</p><button class="button dark" data-bet="clime10" data-side="yes">Explore the market '+icon('arrow')+'</button></div><span class="giant-hash">#</span><div class="challenge-numbers"><strong>8.6M<span>demo views</span></strong><strong>68%<span>chance of 10M</span></strong></div></section>';
}
function cityPage(s){
  const campaign=s.campaigns.find(c=>c.placement==='square'&&c.ends>s.day);
  return heading('Virtu City','Prime digital real estate. A real place in the culture.','<button class="button outline" data-ad="square">Advertise here '+icon('arrow')+'</button>')+
  '<section class="city-overview"><div class="art city-art"></div><div class="city-overview-copy"><span class="small-tag">PRIME SQUARE</span><h2>Your next address<br>is a statement.</h2><p>Storefronts. Studios. Billboards. Possibility.</p><button class="button lime" data-property="prime">Explore Prime Square '+icon('arrow')+'</button></div><button class="map-pin pin-a" data-property="billboard" aria-label="Explore the Skyline Board">'+icon('city')+'<span>Skyline Board</span></button><button class="map-pin pin-b" data-property="nimbus" aria-label="Explore Nimbus Observatory">'+icon('city')+'<span>Nimbus</span></button></section>'+
  '<div class="section-heading"><h2>Find your space</h2><span>'+s.property.length+' owned · 6 locations</span></div><div class="property-grid">'+properties.map(p=>'<article class="panel property-card"><button class="property-preview" data-property="'+p.id+'" aria-label="Explore '+p.name+'">'+propertyImage(p)+'<span class="property-kind">'+p.kind+'</span>'+(s.property.includes(p.id)?'<span class="owned-tag">'+icon('check')+' Owned</span>':'')+'</button><div class="property-content"><small>'+p.district+'</small><h3>'+p.name+'</h3><p>'+p.size+' <span>·</span> '+p.traffic+' demo visits / day</p><div><strong>'+money(p.price)+'</strong><button class="circle-button" data-property="'+p.id+'" aria-label="View '+p.name+'">'+icon('arrow')+'</button></div></div></article>').join('')+'</div>'+
  '<div class="ad-invitation '+(campaign?'booked-ad':'')+'"><div><span class="small-tag">'+(campaign?'Sponsored · Demo placement':'Ad space')+'</span><h2>'+esc(campaign?campaign.name:'Be impossible to scroll past.')+'</h2><p>'+(campaign?'Your billboard is booked through demo day '+campaign.ends+'.':'High-visibility placements across the city and the exchange.')+'</p></div><button class="button purple" data-ad="square">'+(campaign?'View booking':'Book a billboard')+' '+icon('arrow')+'</button></div>';
}
function portfolioPage(s){
  const value=portfolioValue(s),prices=pricesAt(s.day),positions=assets.filter(a=>s.holdings[a.id]>0);
  return heading('Your portfolio','Every move, all in one place.','<button class="button outline" data-reset>'+icon('reset')+' Reset demo</button>')+
  '<section class="portfolio-summary panel"><div><span>Total demo value</span><h2>'+money(value,2)+'</h2><span class="'+(value>=25000?'positive':'negative')+'">'+(value>=25000?'+':'')+number(value-25000,2)+' VC since opening</span></div><div><span>Available VirtuCoin</span><strong>'+money(s.cash,2)+'</strong></div><div><span>Market positions</span><strong>'+positions.length+'</strong></div><div><span>City properties</span><strong>'+s.property.length+'</strong></div></section>'+
  '<div class="section-heading"><h2>Your holdings</h2><button class="text-button" data-view="markets">Explore markets '+icon('arrow')+'</button></div><section class="panel">'+(positions.length?positions.map(a=>'<div class="holding-row"><button class="asset-name" data-asset="'+a.id+'">'+avatar(a)+'<span><strong>'+a.name+'</strong><small>'+s.holdings[a.id]+' shares · $'+a.id+'</small></span></button><strong>'+money(prices[a.id]*s.holdings[a.id],2)+'</strong><button class="button outline small" data-asset="'+a.id+'" data-mode="sell">Manage</button></div>').join(''):'<div class="empty"><span class="stat-icon lavender">'+icon('portfolio')+'</span><h3>Your next move starts here.</h3><p>Explore a market and buy your first shares.</p><button class="button purple" data-view="markets">Find your first market '+icon('arrow')+'</button></div>')+'</section>'+
  '<div class="portfolio-sections"><section><div class="section-heading"><h2>Event positions</h2><span>'+s.bets.length+' bets</span></div><div class="panel">'+(s.bets.length?s.bets.map(b=>'<div class="activity-row"><div><strong>'+events.find(e=>e.id===b.event).title+'</strong><small>'+b.side.toUpperCase()+' · '+number(b.stake,2)+' VC stake</small></div><span class="status '+b.status+'">'+(b.status==='won'?'Won '+number(b.payout,2)+' VC':b.status==='lost'?'Lost':number(b.payout,2)+' VC if correct')+'</span></div>').join(''):'<p class="empty small-empty">Your event positions will appear here.</p>')+'</div></section><section><div class="section-heading"><h2>Your addresses</h2><span>'+s.property.length+' properties</span></div><div class="panel">'+(s.property.length?s.property.map(id=>{const p=properties.find(p=>p.id===id);return '<button class="activity-row clickable" data-property="'+id+'"><div><strong>'+p.name+'</strong><small>'+p.kind+'</small></div><strong>'+money(p.price)+'</strong></button>';}).join(''):'<p class="empty small-empty">Find your first address in Virtu City.</p>')+'</div></section></div>'+
  '<div class="section-heading"><h2>Recent activity</h2></div><section class="panel">'+(s.trades.length?s.trades.slice(0,8).map(t=>'<div class="activity-row"><span class="trade-type">'+icon(t.type==='swap'?'swap':'markets')+'</span><div><strong>'+(t.type==='buy'?'Bought':t.type==='sell'?'Sold':'Traded')+' '+t.quantity+' $'+t.asset+(t.target?' → $'+t.target:'')+'</strong><small>Demo day '+t.day+'</small></div><strong>'+money(t.total,2)+'</strong></div>').join(''):'<p class="empty small-empty">Your trades will appear here.</p>')+'</section>';
}
export function content(s,ui){
  return ui.view==='markets'?markets(s,ui):ui.view==='events'?eventPage(s):ui.view==='challenges'?challengePage(s):ui.view==='city'?cityPage(s):ui.view==='portfolio'?portfolioPage(s):discover(s,ui);
}
export function demoDialog(s){
  return '<h2 id="dialog-title">Welcome to your SMSX demo.</h2><p class="dialog-lead">25,000 VirtuCoin. A whole culture to explore.</p><div class="demo-rules"><p><strong>Make a move.</strong> Buy, sell, or swap shares. Back an event, complete challenges, acquire property, or book a demo ad.</p><p><strong>Move the story forward.</strong> Advance demo days to change market prices and settle events. Outcomes follow a fixed six-day scenario, so the demo is repeatable.</p><p><strong>Explore the overlap.</strong> Fame Farm listings share the exchange with culture-inspired reality mirrors. All prices, audiences, activity, and probabilities are sample data.</p><p><strong>Keep it playful.</strong> No money, deposits, cash-outs, real ownership, or live advertising. Your demo is saved only in this browser.</p></div><div class="day-strip">Demo day '+s.day+' of 6</div><button class="button purple full" data-advance '+(s.day>=6?'disabled':'')+'>Advance to day '+Math.min(6,s.day+1)+' '+icon('arrow')+'</button>';
}
export function assetDialog(s,a,mode='buy'){
  const price=pricesAt(s.day)[a.id];
  return '<div class="asset-detail-head">'+avatar(a,'big')+'<div><span class="small-tag">'+a.world+'</span><h2 id="dialog-title">'+a.name+'</h2><p>$'+a.id+' · '+a.category+'</p></div><button class="watch '+(s.watch.includes(a.id)?'watched':'')+'" data-watch="'+a.id+'" aria-label="Watch '+a.name+'">'+icon('star')+'</button></div><div class="asset-detail-price"><strong>'+money(price,2)+'</strong><span class="'+(a.change>=0?'positive':'negative')+'">'+(a.change>0?'+':'')+number(a.change,2)+'%</span></div>'+chart(assetHistory(a,s.day),a.change>=0?'violet':'coral',true)+'<div class="detail-stats"><span>Volume<strong>'+a.volume+' VC</strong></span><span>Audience<strong>'+a.audience+'</strong></span><span>Attention<strong>'+a.attention+' / 100</strong></span></div><p class="asset-description">'+a.description+'</p><div class="trade-tabs" role="group" aria-label="Trade action">'+['buy','sell','swap'].map(m=>'<button data-trade-mode="'+m+'" data-asset-id="'+a.id+'" class="'+(mode===m?'selected':'')+'" aria-pressed="'+(mode===m)+'">'+(m==='swap'?'Trade':m==='buy'?'Buy':'Sell')+'</button>').join('')+'</div><form id="trade-form" data-mode="'+mode+'" data-asset-id="'+a.id+'"><label for="quantity">Shares <span>'+number(s.holdings[a.id]||0)+' owned</span></label><div class="quantity-field"><input id="quantity" name="quantity" inputmode="numeric" type="number" min="1" max="1000000" step="1" value="10" required><span>shares</span></div><div class="amount-shortcuts">'+[10,50,100].map(q=>'<button type="button" data-quantity="'+q+'">'+q+'</button>').join('')+'<button type="button" data-max="'+a.id+'" data-mode="'+mode+'">Max</button></div>'+(mode==='swap'?'<label for="swap-target">Trade into</label><select id="swap-target" name="target">'+assets.filter(b=>b.id!==a.id).map(b=>'<option value="'+b.id+'">'+b.name+' · $'+b.id+'</option>').join('')+'</select>':'')+'<div class="trade-total"><span>'+(mode==='swap'?'Trade value':mode==='sell'?'You receive':'Total')+'</span><strong id="trade-total">'+money(price*10,2)+'</strong></div><p id="swap-estimate" class="field-hint"></p><p class="field-hint">Available: '+number(s.cash,2)+' VC · No demo fees</p><p id="form-error" class="form-error" role="alert"></p><button class="button '+(mode==='sell'?'coral':'purple')+' full" type="submit">'+(mode==='buy'?'Buy':mode==='sell'?'Sell':'Trade')+' $'+a.id+' '+icon(mode==='swap'?'swap':'arrow')+'</button><small class="transaction-note">Simulated transaction · VirtuCoin has no cash value</small></form>';
}
export function betDialog(s,e,side='yes'){
  const closed=s.day>=e.closes;
  return '<span class="small-tag">'+e.category+' · Demo event</span><h2 id="dialog-title">'+e.title+'</h2><p class="dialog-lead">'+e.detail+'</p>'+prediction(s,e,true)+
  (!closed?'<form id="bet-form" data-event-id="'+e.id+'" data-side="'+side+'"><label for="stake">Stake <span>Backing '+side.toUpperCase()+'</span></label><div class="quantity-field"><input id="stake" name="stake" type="number" min="10" step="0.01" value="100" required><span>VC</span></div><div class="amount-shortcuts">'+[100,250,500].map(n=>'<button type="button" data-stake="'+n+'">'+n+' VC</button>').join('')+'</div><div class="trade-total"><span>Total payout if correct</span><strong id="bet-payout">'+money(100/((side==='yes'?e.yes:100-e.yes)/100),2)+'</strong></div><p class="field-hint">Includes your stake. You lose your stake if incorrect.<br>Fixed demo outcome · Settles on demo day '+e.closes+'.</p><p id="form-error" class="form-error" role="alert"></p><button type="submit" class="button '+(side==='yes'?'lime':'coral')+' full">Back '+side.toUpperCase()+' '+icon('arrow')+'</button><small class="transaction-note">Demo only · No real-money betting</small></form>':'<button class="button purple full" data-view="events">Explore other events</button>');
}
export function propertyDialog(s,p){
  const owned=s.property.includes(p.id);
  return '<div class="dialog-property-art">'+propertyImage(p)+'<span class="property-kind">'+p.district+'</span></div><span class="small-tag">'+p.kind+'</span><h2 id="dialog-title">'+p.name+'</h2><p class="dialog-lead">'+p.description+'</p><div class="detail-stats"><span>Space<strong>'+p.size+'</strong></span><span>Demo visits / day<strong>'+p.traffic+'</strong></span></div><div class="trade-total"><span>'+(owned?'Your property value':'Acquisition price')+'</span><strong>'+money(p.price)+'</strong></div><p class="field-hint">Available: '+number(s.cash,2)+' VC. Demo ownership is recorded in this browser; no rent or income is accrued.</p><p id="form-error" class="form-error" role="alert"></p><button class="button '+(owned?'outline':'purple')+' full" data-acquire="'+p.id+'" data-owned="'+owned+'">'+(owned?'Sell property for '+number(p.price)+' VC':'Acquire property')+' '+icon('arrow')+'</button><small class="transaction-note">Fictional property · No real ownership rights</small>';
}
export function adDialog(s,id='discover'){
  const p=placements.find(p=>p.id===id),booking=s.campaigns.find(c=>c.placement===id&&c.ends>s.day);
  return '<span class="small-tag">SMSX Ad Space</span><h2 id="dialog-title">Attention has an address.</h2><p class="dialog-lead">Try a placement across the exchange. See your campaign inside the demo.</p><form id="ad-form"><label for="placement">Placement</label><select id="placement" name="placement">'+placements.map(a=>'<option value="'+a.id+'" '+(a.id===id?'selected':'')+'>'+a.name+'</option>').join('')+'</select><div class="ad-preview"><span>Sponsored · Demo</span><h3>'+esc(booking?booking.name:'YOUR BRAND HERE')+'</h3><p>'+p.description+'</p></div><div class="detail-stats"><span>Sample reach<strong>'+p.reach+'</strong></span><span>Duration<strong>3 demo days</strong></span><span>Booking fee<strong>'+p.cost+' VC</strong></span></div>'+(booking?'<div class="booking-status">'+icon('check')+' Booked through demo day '+booking.ends+'</div><button type="button" class="button purple full" data-view="'+(id==='square'?'city':id==='event'?'events':'discover')+'">See your placement '+icon('arrow')+'</button>':'<label for="campaign-name">Campaign name</label><input id="campaign-name" name="name" type="text" minlength="2" maxlength="40" placeholder="Your next big thing" required><p class="field-hint">Available: '+number(s.cash,2)+' VC. Booking is a demo expense.</p><p id="form-error" class="form-error" role="alert"></p><button class="button purple full" type="submit">Book for '+p.cost+' VC '+icon('arrow')+'</button>')+'<small class="transaction-note">Simulation only · No ad is published outside this demo</small></form>';
}
